{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE MultiParamTypeClasses #-}

{- |
Module      : Language.Egison.Math.CAS
Licence     : MIT

This module defines the new CASValue data type for the computer algebra system.
The type structure directly determines the runtime internal representation.

Key design principles:
- Type composition determines normal form (e.g., Poly (Div Integer) vs Div (Poly Integer))
- Supports Laurent polynomials (negative exponents allowed in monomials)
- Constructive: coefficients can be recursively nested CASValues
-}

module Language.Egison.Math.CAS
    ( -- * Core data types
      CASValue (..)
    , CASTerm (..)
    , Monomial
    -- * Smart constructors
    , casInteger
    , casFactor
    , casPoly
    , casDiv
    , casTerm
    -- * Arithmetic operations
    , casPlus
    , casMult
    , casNegate
    , casMinus
    , casDivide
    , casPower
    , casNumerator
    , casDenominator
    -- * Normalization
    , casNormalize
    , casNormalizePoly
    -- * Predicates
    , casIsZero
    -- * GCD operations
    , casGcd
    , casTermsGcd
    -- * Conversion from/to ScalarData (for migration)
    , scalarDataToCASValue
    , casValueToScalarData
    ) where

import           Data.List (sortBy, groupBy)
import           Data.Ord (comparing)
import           Data.Function (on)

import           Language.Egison.Math.Expr (SymbolExpr(..), Monomial, ScalarData(..), PolyExpr(..), TermExpr(..))

-- | CASValue represents mathematical values in the CAS.
-- The structure is compositional: each constructor has a well-defined semantics.
data CASValue
  = CASInteger Integer
    -- ^ Base case: an integer value
  | CASFactor SymbolExpr
    -- ^ An atomic factor (generated by quote operator ')
    -- Represents a symbol or function application that is not yet expanded
  | CASPoly [CASTerm]
    -- ^ A polynomial (sum of terms). Empty list represents zero.
    -- Supports Laurent polynomials: monomial exponents can be negative.
  | CASDiv CASValue CASValue
    -- ^ A quotient: numerator / denominator
    -- Only needed when denominator is non-monomial
  deriving (Eq, Show)

-- | CASTerm represents a single term in a polynomial: coefficient × monomial
-- The coefficient is a CASValue, enabling nested polynomial structures.
data CASTerm = CASTerm CASValue Monomial
  deriving (Eq, Show)

--------------------------------------------------------------------------------
-- Smart Constructors
--------------------------------------------------------------------------------

-- | Create an integer CASValue
casInteger :: Integer -> CASValue
casInteger = CASInteger

-- | Create a factor CASValue from a SymbolExpr
casFactor :: SymbolExpr -> CASValue
casFactor = CASFactor

-- | Create a polynomial CASValue, normalizing the terms
casPoly :: [CASTerm] -> CASValue
casPoly terms = casNormalize (CASPoly terms)

-- | Create a division CASValue, simplifying if possible
casDiv :: CASValue -> CASValue -> CASValue
casDiv num denom = casNormalize (CASDiv num denom)

-- | Create a term
casTerm :: CASValue -> Monomial -> CASTerm
casTerm = CASTerm

--------------------------------------------------------------------------------
-- Predicates
--------------------------------------------------------------------------------

-- | Check if a CASValue is zero
casIsZero :: CASValue -> Bool
casIsZero (CASInteger 0) = True
casIsZero (CASPoly [])   = True
casIsZero (CASDiv n _)   = casIsZero n
casIsZero _              = False

-- | Check if a CASValue is one
casIsOne :: CASValue -> Bool
casIsOne (CASInteger 1)                     = True
casIsOne (CASPoly [CASTerm (CASInteger 1) []]) = True
casIsOne _                                  = False

--------------------------------------------------------------------------------
-- Arithmetic Operations
--------------------------------------------------------------------------------

-- | Add two CASValues
casPlus :: CASValue -> CASValue -> CASValue
casPlus a b = casNormalize (casPlus' a b)

casPlus' :: CASValue -> CASValue -> CASValue
-- Integer + Integer
casPlus' (CASInteger a) (CASInteger b) = CASInteger (a + b)

-- Poly + Poly
casPlus' (CASPoly ts1) (CASPoly ts2) = CASPoly (ts1 ++ ts2)

-- Integer + Poly: embed integer as polynomial term
casPlus' (CASInteger n) (CASPoly ts) = CASPoly (CASTerm (CASInteger n) [] : ts)
casPlus' (CASPoly ts) (CASInteger n) = CASPoly (CASTerm (CASInteger n) [] : ts)

-- Div + Div: cross-multiply and add numerators
casPlus' (CASDiv n1 d1) (CASDiv n2 d2) =
  CASDiv (casPlus' (casMult' n1 d2) (casMult' n2 d1)) (casMult' d1 d2)

-- Div + other: embed other as Div
casPlus' (CASDiv n d) other = CASDiv (casPlus' n (casMult' other d)) d
casPlus' other (CASDiv n d) = CASDiv (casPlus' (casMult' other d) n) d

-- Factor handling: lift to polynomial before operation
casPlus' (CASFactor sym) other = casPlus' (liftFactorToPoly sym) other
casPlus' other (CASFactor sym) = casPlus' other (liftFactorToPoly sym)

-- | Negate a CASValue
casNegate :: CASValue -> CASValue
casNegate (CASInteger n)  = CASInteger (-n)
casNegate (CASPoly terms) = CASPoly (map negateTerm terms)
  where
    negateTerm (CASTerm coeff mono) = CASTerm (casNegate coeff) mono
casNegate (CASDiv n d)    = CASDiv (casNegate n) d
casNegate (CASFactor sym) = CASPoly [CASTerm (CASInteger (-1)) [(sym, 1)]]

-- | Subtract two CASValues
casMinus :: CASValue -> CASValue -> CASValue
casMinus a b = casPlus a (casNegate b)

-- | Multiply two CASValues
casMult :: CASValue -> CASValue -> CASValue
casMult a b = casNormalize (casMult' a b)

casMult' :: CASValue -> CASValue -> CASValue
-- Integer * Integer
casMult' (CASInteger a) (CASInteger b) = CASInteger (a * b)

-- Integer * Poly: scale all coefficients
casMult' (CASInteger n) (CASPoly ts) = CASPoly (map (scaleTerm n) ts)
  where
    scaleTerm k (CASTerm coeff mono) = CASTerm (casMult' (CASInteger k) coeff) mono
casMult' (CASPoly ts) (CASInteger n) = casMult' (CASInteger n) (CASPoly ts)

-- Poly * Poly: distribute
casMult' (CASPoly []) _ = CASPoly []
casMult' _ (CASPoly []) = CASPoly []
casMult' (CASPoly ts1) (CASPoly ts2) =
  CASPoly [multTerms t1 t2 | t1 <- ts1, t2 <- ts2]
  where
    multTerms (CASTerm c1 m1) (CASTerm c2 m2) =
      CASTerm (casMult' c1 c2) (combineMonomials m1 m2)

-- Div * Div: multiply numerators and denominators
casMult' (CASDiv n1 d1) (CASDiv n2 d2) =
  CASDiv (casMult' n1 n2) (casMult' d1 d2)

-- Div * other: multiply into numerator
casMult' (CASDiv n d) other = CASDiv (casMult' n other) d
casMult' other (CASDiv n d) = CASDiv (casMult' other n) d

-- Factor handling: lift to polynomial before operation
casMult' (CASFactor sym) other = casMult' (liftFactorToPoly sym) other
casMult' other (CASFactor sym) = casMult' other (liftFactorToPoly sym)

-- | Lift a Factor to a polynomial: sym → 1 * sym^1
liftFactorToPoly :: SymbolExpr -> CASValue
liftFactorToPoly sym = CASPoly [CASTerm (CASInteger 1) [(sym, 1)]]

-- | Combine two monomials by adding exponents of matching symbols
combineMonomials :: Monomial -> Monomial -> Monomial
combineMonomials m1 m2 = foldr insertSymbol m2 m1
  where
    insertSymbol (sym, expo) mono =
      case lookup sym mono of
        Just _  -> map (\(s, e) -> if s == sym then (s, e + expo) else (s, e)) mono
        Nothing -> (sym, expo) : mono

-- | Divide two CASValues: a / b
casDivide :: CASValue -> CASValue -> CASValue
casDivide a b = casNormalize (CASDiv a b)

-- | Raise a CASValue to an integer power
casPower :: CASValue -> Integer -> CASValue
casPower _ 0 = CASInteger 1
casPower x 1 = x
casPower x n
  | n > 0     = casMult x (casPower x (n - 1))
  | otherwise = casDivide (CASInteger 1) (casPower x (-n))  -- Negative power

-- | Get the numerator of a CASValue
casNumerator :: CASValue -> CASValue
casNumerator (CASDiv num _) = num
casNumerator x              = x  -- Non-Div values are their own numerator

-- | Get the denominator of a CASValue
casDenominator :: CASValue -> CASValue
casDenominator (CASDiv _ denom) = denom
casDenominator _                = CASInteger 1  -- Non-Div values have denominator 1

--------------------------------------------------------------------------------
-- Normalization
--------------------------------------------------------------------------------

-- | Normalize a CASValue
casNormalize :: CASValue -> CASValue
casNormalize (CASInteger n) = CASInteger n
casNormalize (CASFactor sym) = CASFactor sym
casNormalize (CASPoly terms) = casNormalizePoly terms
casNormalize (CASDiv num denom) = casNormalizeDiv num denom

-- | Normalize a polynomial
-- Steps:
-- 1. Fold symbols within each term (x * x^2 → x^3)
-- 2. Remove zero-exponent symbols
-- 3. Fold terms with equal monomials
-- 4. Remove zero-coefficient terms
-- 5. Sort terms in descending order
casNormalizePoly :: [CASTerm] -> CASValue
casNormalizePoly terms =
  let -- Normalize each term's monomial
      terms1 = map normalizeTermMonomial terms
      -- Fold terms with equal monomials
      terms2 = foldTerms terms1
      -- Remove zero-coefficient terms
      terms3 = filter (not . isZeroTerm) terms2
      -- Sort in descending order (standard polynomial order)
      terms4 = sortTermsDescending terms3
  in case terms4 of
       []  -> CASPoly []
       [CASTerm coeff []] | isIntegerCoeff coeff -> extractInteger coeff
       ts  -> CASPoly ts
  where
    isZeroTerm (CASTerm coeff _) = casIsZero coeff
    isIntegerCoeff (CASInteger _) = True
    isIntegerCoeff _ = False
    extractInteger (CASInteger n) = CASInteger n
    extractInteger _ = error "extractInteger: not an integer"

-- | Normalize a term's monomial: combine duplicate symbols, remove zero exponents
normalizeTermMonomial :: CASTerm -> CASTerm
normalizeTermMonomial (CASTerm coeff mono) =
  let -- Fold duplicate symbols
      mono1 = foldMonomialSymbols mono
      -- Remove zero-exponent symbols
      mono2 = filter (\(_, exp) -> exp /= 0) mono1
      -- Normalize the coefficient recursively
      coeff' = casNormalize coeff
  in CASTerm coeff' mono2

-- | Fold duplicate symbols in a monomial by adding their exponents
foldMonomialSymbols :: Monomial -> Monomial
foldMonomialSymbols mono =
  let grouped = groupBy ((==) `on` fst) (sortBy (comparing (show . fst)) mono)
  in concatMap combineGroup grouped
  where
    combineGroup :: [(SymbolExpr, Integer)] -> [(SymbolExpr, Integer)]
    combineGroup [] = []
    combineGroup grp@((sym, _):_) = [(sym, sum (map snd grp))]

-- | Fold terms with equal monomials by adding their coefficients
foldTerms :: [CASTerm] -> [CASTerm]
foldTerms terms =
  let grouped = groupBy equalMonos (sortBy (comparing termMonoKey) terms)
  in concatMap combineTerms grouped
  where
    -- Use show-based key for consistent ordering
    termMonoKey (CASTerm _ m) = map (\(s, e) -> (show s, e)) (sortBy (comparing (show . fst)) m)
    termMono (CASTerm _ m) = sortBy (comparing (show . fst)) m
    equalMonos t1 t2 = termMono t1 == termMono t2
    combineTerms [] = []
    combineTerms grp@((CASTerm _ m):_) =
      let mono = sortBy (comparing (show . fst)) m
          coeffSum = foldr casPlus' (CASInteger 0) [c | CASTerm c _ <- grp]
      in [CASTerm (casNormalize coeffSum) mono]

-- | Sort terms in descending order (highest degree first)
-- Order: by total degree, then lexicographically by symbols
sortTermsDescending :: [CASTerm] -> [CASTerm]
sortTermsDescending = sortBy (flip (comparing termDegree) <> flip (comparing termSymbolsKey))
  where
    termDegree (CASTerm _ mono) = sum (map snd mono)
    -- Use show-based key for consistent lexicographic ordering
    termSymbolsKey (CASTerm _ mono) = map (\(s, e) -> (show s, e)) (sortBy (comparing (show . fst)) mono)

-- | Normalize a division
-- Steps:
-- 1. If denominator is 1, return numerator
-- 2. If numerator is 0, return 0
-- 3. Simplify using GCD
casNormalizeDiv :: CASValue -> CASValue -> CASValue
casNormalizeDiv num denom =
  let num' = casNormalize num
      denom' = casNormalize denom
  in case (num', denom') of
       -- Zero numerator
       (n, _) | casIsZero n -> CASInteger 0
       -- Denominator is 1
       (n, d) | casIsOne d -> n
       -- Integer / Integer: reduce by GCD
       (CASInteger n, CASInteger d) ->
         let g = gcd n d
             n' = n `div` g
             d' = d `div` g
         in if d' == 1
            then CASInteger n'
            else CASDiv (CASInteger n') (CASInteger d')
       -- Poly / Poly: try to reduce by monomial GCD
       (CASPoly ts1, CASPoly ts2) ->
         let (ts1', ts2') = simplifyPolyDiv ts1 ts2
         in case (ts1', ts2') of
              (ts1'', [CASTerm (CASInteger 1) []]) -> casNormalizePoly ts1''
              _ -> CASDiv (casNormalizePoly ts1') (casNormalizePoly ts2')
       -- Default: no simplification
       _ -> CASDiv num' denom'

-- | Simplify polynomial division by extracting common monomial GCD
simplifyPolyDiv :: [CASTerm] -> [CASTerm] -> ([CASTerm], [CASTerm])
simplifyPolyDiv [] ts2 = ([], ts2)
simplifyPolyDiv ts1 [] = (ts1, [])
simplifyPolyDiv ts1 ts2 =
  let gcdTerm = casTermsGcd (ts1 ++ ts2)
  in (map (`divideTermBy` gcdTerm) ts1, map (`divideTermBy` gcdTerm) ts2)

--------------------------------------------------------------------------------
-- GCD Operations
--------------------------------------------------------------------------------

-- | GCD of two CASValues (for coefficient reduction)
-- Initial implementation: only handles CASInteger, others return 1
casGcd :: CASValue -> CASValue -> CASValue
casGcd (CASInteger a) (CASInteger b) = CASInteger (gcd a b)
casGcd _ _ = CASInteger 1  -- Fallback: GCD = 1 for other coefficient types

-- | Compute the GCD of a list of terms (coefficient GCD + monomial GCD)
casTermsGcd :: [CASTerm] -> CASTerm
casTermsGcd [] = CASTerm (CASInteger 1) []
casTermsGcd [t] = t
casTermsGcd terms = foldl1 termGcd terms
  where
    termGcd (CASTerm c1 m1) (CASTerm c2 m2) =
      CASTerm (casGcd c1 c2) (monoGcd m1 m2)

-- | GCD of two monomials: take minimum exponent for each shared symbol
monoGcd :: Monomial -> Monomial -> Monomial
monoGcd [] _ = []
monoGcd ((sym, exp):rest) mono =
  case lookup sym mono of
    Just exp' -> (sym, min exp exp') : monoGcd rest mono
    Nothing   -> monoGcd rest mono

-- | Divide a term by another term (for GCD reduction)
divideTermBy :: CASTerm -> CASTerm -> CASTerm
divideTermBy (CASTerm coeff1 mono1) (CASTerm coeff2 mono2) =
  CASTerm (divCoeff coeff1 coeff2) (divMono mono1 mono2)
  where
    divCoeff (CASInteger a) (CASInteger b) = CASInteger (a `div` b)
    divCoeff a _ = a  -- Fallback: no division for other types

    divMono m [] = m
    divMono m ((sym, expo):rest) =
      let m' = map (\(s, e) -> if s == sym then (s, e - expo) else (s, e)) m
      in divMono m' rest

--------------------------------------------------------------------------------
-- Conversion Functions (for migration from ScalarData)
--------------------------------------------------------------------------------

-- | Convert ScalarData to CASValue
-- This is used during the migration period to convert existing code
scalarDataToCASValue :: ScalarData -> CASValue
scalarDataToCASValue (Div num denom) =
  casNormalize $ CASDiv (polyExprToCASValue num) (polyExprToCASValue denom)

-- | Convert PolyExpr to CASValue (as a polynomial)
polyExprToCASValue :: PolyExpr -> CASValue
polyExprToCASValue (Plus []) = CASPoly []
polyExprToCASValue (Plus terms) = CASPoly (map termExprToCAS terms)

-- | Convert TermExpr to CASTerm
termExprToCAS :: TermExpr -> CASTerm
termExprToCAS (Term coeff mono) = CASTerm (CASInteger coeff) mono

-- | Convert CASValue back to ScalarData
-- This is needed for compatibility with code that still uses ScalarData
casValueToScalarData :: CASValue -> ScalarData
casValueToScalarData (CASInteger n) =
  if n == 0
    then Div (Plus []) (Plus [Term 1 []])
    else Div (Plus [Term n []]) (Plus [Term 1 []])
casValueToScalarData (CASFactor sym) =
  Div (Plus [Term 1 [(sym, 1)]]) (Plus [Term 1 []])
casValueToScalarData (CASPoly terms) =
  Div (Plus (map casTermToTermExpr terms)) (Plus [Term 1 []])
casValueToScalarData (CASDiv num denom) =
  let Div numPoly _ = casValueToScalarData num
      Div denomPoly _ = casValueToScalarData denom
  in Div numPoly denomPoly

-- | Convert CASTerm to TermExpr
-- Note: This only works for terms with CASInteger coefficients
casTermToTermExpr :: CASTerm -> TermExpr
casTermToTermExpr (CASTerm (CASInteger coeff) mono) = Term coeff mono
casTermToTermExpr (CASTerm _ _) =
  error "casTermToTermExpr: non-integer coefficient (nested polynomials not supported in ScalarData)"
