{-# LANGUAGE FlexibleInstances     #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE PatternSynonyms       #-}
{-# LANGUAGE QuasiQuotes           #-}

{- |
Module      : Language.Egison.Math.CAS
Licence     : MIT

This module defines the new CASValue data type for the computer algebra system.
The type structure directly determines the runtime internal representation.

Key design principles:
- Type composition determines normal form (e.g., Poly (Frac Integer) vs Frac (Poly Integer))
- Supports Laurent polynomials (negative exponents allowed in monomials)
- Constructive: coefficients can be recursively nested CASValues
-}

module Language.Egison.Math.CAS
    ( -- * Core data types
      CASValue (..)
    , CASTerm (..)
    , Monomial
    , SymbolExpr (..)
    , Id
    , makeApplyExpr
    -- * Smart constructors
    , casInteger
    , casFactor
    , casPoly
    , casFrac
    , casTerm
    -- * Arithmetic operations
    , casPlus
    , casMult
    , casNegate
    , casMinus
    , casDivide
    , casPower
    , casNumerator
    , casDenominator
    -- * Observed type (Phase 8)
    , prettyTypeOf
    , casAtomSet
    , casDifferentialClosed
    -- * Normalization
    , casNormalize
    , casNormalizePoly
    -- * Predicates
    , casIsZero
    , casIsAtom
    -- * Pretty printing
    , prettyCAS
    -- * GCD operations
    , casGcd
    , casTermsGcd
    -- * Pattern synonyms for CASValue
    , pattern CASZero
    , pattern CASSingleSymbol
    , pattern CASSingleTerm
    -- * Pattern matching (control-egison)
    , CASM (..)
    , CASTermM (..)
    , CASSymbolM (..)
    , casTerm'
    , casTerm'M
    , casTermM
    , casSymbol
    , casSymbolM
    , casFunc
    , casFuncM
    , casApply1
    , casApply1M
    , casApply2
    , casApply2M
    , casApply3
    , casApply3M
    , casApply4
    , casApply4M
    , casQuote
    , casNegQuote
    , casNegQuoteM
    , casQuoteFunction
    , casQuoteFunctionM
    , casEqualMonomial
    , casEqualMonomialM
    , casZero
    , casZeroM
    , casSingleTerm
    , casSingleTermM
    ) where

import           Data.List (sortBy, groupBy)
import           Data.Ord (comparing)
import           Data.Function (on)

import           Control.Egison
import           Control.Monad (MonadPlus (..))

import           Language.Egison.IExpr (Index (..))
import {-# SOURCE #-} Language.Egison.Data (WHNFData, prettyFunctionName)

-- | CASValue represents mathematical values in the CAS.
-- The structure is compositional: each constructor has a well-defined semantics.
data CASValue
  = CASInteger Integer
    -- ^ Base case: an integer value
  | CASFactor SymbolExpr
    -- ^ An atomic factor (generated by quote operator ')
    -- Represents a symbol or function application that is not yet expanded
  | CASPoly [CASTerm]
    -- ^ A polynomial (sum of terms). Empty list represents zero.
    -- Supports Laurent polynomials: monomial exponents can be negative.
  | CASFrac CASValue CASValue
    -- ^ A quotient: numerator / denominator
    -- Only needed when denominator is non-monomial
  deriving (Eq, Show)

-- | CASTerm represents a single term in a polynomial: coefficient × monomial
-- The coefficient is a CASValue, enabling nested polynomial structures.
data CASTerm = CASTerm CASValue Monomial
  deriving (Eq, Show)

-- | We choose the definition 'monomials' without its coefficients.
-- ex. 2 x^2 y^3 is *not* a monomial. x^2 t^3 is a monomial.
type Monomial = [(SymbolExpr, Integer)]

-- | Identifier type for symbols
type Id = String

-- | SymbolExpr represents atomic symbolic expressions in the CAS.
-- NOTE: SymbolExpr uses CASValue for function arguments (Apply1-4, Quote, FunctionData).
data SymbolExpr
  = Symbol Id String [Index CASValue]
  | Apply1 CASValue CASValue
  | Apply2 CASValue CASValue CASValue
  | Apply3 CASValue CASValue CASValue CASValue
  | Apply4 CASValue CASValue CASValue CASValue CASValue
  | Quote CASValue                     -- For backtick quote: `expr
  | QuoteFunction WHNFData             -- For single quote on functions: 'func
  | FunctionData CASValue [CASValue]   -- fnname args

-- Manual Eq instance (QuoteFunction comparison uses function name)
instance Eq SymbolExpr where
  Symbol id1 s1 js1 == Symbol id2 s2 js2 = id1 == id2 && s1 == s2 && js1 == js2
  Apply1 f1 a1 == Apply1 f2 a2 = f1 == f2 && a1 == a2
  Apply2 f1 a1 b1 == Apply2 f2 a2 b2 = f1 == f2 && a1 == a2 && b1 == b2
  Apply3 f1 a1 b1 c1 == Apply3 f2 a2 b2 c2 = f1 == f2 && a1 == a2 && b1 == b2 && c1 == c2
  Apply4 f1 a1 b1 c1 d1 == Apply4 f2 a2 b2 c2 d2 = f1 == f2 && a1 == a2 && b1 == b2 && c1 == c2 && d1 == d2
  Quote m1 == Quote m2 = m1 == m2
  QuoteFunction whnf1 == QuoteFunction whnf2 =
    case (prettyFunctionName whnf1, prettyFunctionName whnf2) of
      (Just n1, Just n2) -> n1 == n2
      _ -> False  -- Anonymous functions are never equal
  FunctionData n1 k1 == FunctionData n2 k2 = n1 == n2 && k1 == k2
  _ == _ = False

instance Show SymbolExpr where
  show = prettySymbolExpr

-- | Pretty print a SymbolExpr
prettySymbolExpr :: SymbolExpr -> String
prettySymbolExpr (Symbol _ (':':':':':':_) []) = "#"
prettySymbolExpr (Symbol _ s [])               = s
prettySymbolExpr (Symbol _ s js)               = s ++ concatMap showIndex js
  where
    showIndex (Sup i)    = "~" ++ prettyCAS' i
    showIndex (Sub i)    = "_" ++ prettyCAS' i
    showIndex (SupSub i) = "~_" ++ prettyCAS' i
    showIndex (DF _ _)   = ""
    showIndex (User i)   = "|" ++ prettyCAS' i
prettySymbolExpr (Apply1 fn a1)                = unwords [prettyCAS' fn, prettyCAS' a1]
prettySymbolExpr (Apply2 fn a1 a2)             = unwords [prettyCAS' fn, prettyCAS' a1, prettyCAS' a2]
prettySymbolExpr (Apply3 fn a1 a2 a3)          = unwords [prettyCAS' fn, prettyCAS' a1, prettyCAS' a2, prettyCAS' a3]
prettySymbolExpr (Apply4 fn a1 a2 a3 a4)       = unwords [prettyCAS' fn, prettyCAS' a1, prettyCAS' a2, prettyCAS' a3, prettyCAS' a4]
prettySymbolExpr (Quote mExprs)                = "`" ++ prettyCAS' mExprs
prettySymbolExpr (QuoteFunction whnf)          = "'" ++ maybe "<function>" id (prettyFunctionName whnf)
prettySymbolExpr (FunctionData name args)      = unwords (prettyCAS name : map prettyCAS' args)

-- | Pretty print a CASValue (basic version for SymbolExpr Show instance)
prettyCAS :: CASValue -> String
prettyCAS (CASInteger n) = show n
prettyCAS (CASFactor sym) = prettySymbolExpr sym
prettyCAS (CASPoly []) = "0"
prettyCAS (CASPoly terms) = prettyTerms terms
  where
    prettyTerms [] = "0"
    prettyTerms (t:ts) = prettyTerm t ++ concatMap withSign ts
    withSign term@(CASTerm coeff _)
      | isNegative coeff = " - " ++ prettyTerm (negateCAST term)
      | otherwise = " + " ++ prettyTerm term
    prettyTerm (CASTerm coeff []) = prettyCAS coeff
    prettyTerm (CASTerm (CASInteger 1) mono) = prettyMono mono
    prettyTerm (CASTerm (CASInteger (-1)) mono) = "- " ++ prettyMono mono
    prettyTerm (CASTerm coeff mono) = prettyCAS coeff ++ " * " ++ prettyMono mono
    prettyMono mono = unwords (map prettyPow mono)
    prettyPow (sym, 1) = prettySymbolExpr sym
    prettyPow (sym, n) = prettyCAS' (CASFactor sym) ++ "^" ++ show n
    isNegative (CASInteger n) = n < 0
    isNegative _ = False
    negateCAST (CASTerm (CASInteger n) m) = CASTerm (CASInteger (-n)) m
    negateCAST t = t
prettyCAS (CASFrac num denom) = prettyCAS' num ++ " / " ++ prettyCAS' denom

prettyCAS' :: CASValue -> String
prettyCAS' v@(CASInteger _) = prettyCAS v
prettyCAS' v@(CASFactor _) = prettyCAS v
prettyCAS' v = "(" ++ prettyCAS v ++ ")"

-- | Compute the observed type of a CASValue and pretty print it.
-- The observed type is the most specific static type that the value
-- inhabits, computed bottom-up from the runtime structure.
--   CASInteger _      → "Integer"
--   CASFactor (Symbol ...)
--                     → "Symbol"
--   CASFactor _       → "Factor"
--   CASPoly []        → "Integer"   (canonical zero)
--   CASPoly terms     → "Poly C [atoms]" where C is the join of term coefficient
--                       types and atoms is the sorted list of distinct flat atoms
--   CASFrac n d       → "Frac (typeOf n)" if d is integer/poly with single term,
--                       otherwise "Frac (Poly typeOf-num [..])"
prettyTypeOf :: CASValue -> String
prettyTypeOf (CASInteger _) = "Integer"
prettyTypeOf (CASFactor (Symbol _ _ _)) = "Symbol"
prettyTypeOf (CASFactor _) = "Factor"
prettyTypeOf (CASPoly []) = "Integer"
prettyTypeOf (CASPoly terms) =
  let coeffTypes = map (\(CASTerm c _) -> prettyTypeOf c) terms
      coeffType  = joinObservedTypes coeffTypes
      atoms      = collectAtoms terms
      atomStr    = if null atoms
                     then "[]"
                     else "[" ++ commaSep atoms ++ "]"
   in "Poly " ++ parenIfApp coeffType ++ " " ++ atomStr
prettyTypeOf (CASFrac n d) =
  "Frac " ++ parenIfApp inner
  where
    nT = prettyTypeOf n
    dT = prettyTypeOf d
    -- If numerator and denominator share the observed type, that's the inner;
    -- otherwise widen to MathValue.
    inner = if nT == dT then nT else "MathValue"

-- | Pretty join of observed types of multiple coefficients. The simple rule:
-- if all are equal, use that. Otherwise widen to the broadest seen.
joinObservedTypes :: [String] -> String
joinObservedTypes [] = "Integer"
joinObservedTypes ts
  | all (== head ts) ts = head ts
  | otherwise = "MathValue"

-- | Phase 8 differential closure: collect the set of atoms (as their canonical
-- pretty form) appearing in a CASValue's monomials, recursing into nested
-- coefficients. The result is a sorted list of unique atom names.
casAtomSet :: CASValue -> [String]
casAtomSet (CASInteger _) = []
casAtomSet (CASFactor sym) = [prettySymbolExpr sym]
casAtomSet (CASPoly terms) =
  let atomNames = concat
        [ map (prettySymbolExpr . fst) mono ++ casAtomSet coeff
        | CASTerm coeff mono <- terms
        ]
  in unique (sortBy compare atomNames)
  where
    unique [] = []
    unique (x:xs) = x : unique (dropWhile (== x) xs)
casAtomSet (CASFrac n d) =
  let combined = casAtomSet n ++ casAtomSet d
  in unique (sortBy compare combined)
  where
    unique [] = []
    unique (x:xs) = x : unique (dropWhile (== x) xs)

-- | Check whether differentiation preserved the atom set of the input.
-- Used by the `differentialClosed` primitive: the result is true iff the
-- atom set of `output` is a subset of that of `input` (no new atoms
-- introduced by `∂/∂`).
casDifferentialClosed :: CASValue -> CASValue -> Bool
casDifferentialClosed input output =
  let inA  = casAtomSet input
      outA = casAtomSet output
  in all (`elem` inA) outA

-- | Collect distinct atom names from a list of CASTerm monomials.
-- Returns a sorted list of pretty atom forms (`x`, `sin x`, etc.).
collectAtoms :: [CASTerm] -> [String]
collectAtoms terms =
  let atomNames = [prettySymbolExpr s | CASTerm _ mono <- terms, (s, _) <- mono]
  in unique (sortBy compare atomNames)
  where
    unique [] = []
    unique (x:xs) = x : unique (dropWhile (== x) xs)

-- | Comma-separate strings.
commaSep :: [String] -> String
commaSep []     = ""
commaSep [x]    = x
commaSep (x:xs) = x ++ ", " ++ commaSep xs

-- | Wrap in parens if the type printed contains a space (i.e. an application).
parenIfApp :: String -> String
parenIfApp s
  | ' ' `elem` s = "(" ++ s ++ ")"
  | otherwise    = s

-- | Helper function to create Apply constructors based on argument count
makeApplyExpr :: CASValue -> [CASValue] -> SymbolExpr
makeApplyExpr fn [a1] = Apply1 fn a1
makeApplyExpr fn [a1, a2] = Apply2 fn a1 a2
makeApplyExpr fn [a1, a2, a3] = Apply3 fn a1 a2 a3
makeApplyExpr fn [a1, a2, a3, a4] = Apply4 fn a1 a2 a3 a4
makeApplyExpr _ _ = error "makeApplyExpr: unsupported number of arguments (must be 1-4)"

--------------------------------------------------------------------------------
-- Smart Constructors
--------------------------------------------------------------------------------

-- | Create an integer CASValue
casInteger :: Integer -> CASValue
casInteger = CASInteger

-- | Create a factor CASValue from a SymbolExpr
casFactor :: SymbolExpr -> CASValue
casFactor = CASFactor

-- | Create a polynomial CASValue, normalizing the terms
casPoly :: [CASTerm] -> CASValue
casPoly terms = casNormalize (CASPoly terms)

-- | Create a division CASValue, simplifying if possible
casFrac :: CASValue -> CASValue -> CASValue
casFrac num denom = casNormalize (CASFrac num denom)

-- | Create a term
casTerm :: CASValue -> Monomial -> CASTerm
casTerm = CASTerm

--------------------------------------------------------------------------------
-- Predicates
--------------------------------------------------------------------------------

-- | Check if a CASValue is zero
casIsZero :: CASValue -> Bool
casIsZero (CASInteger 0) = True
casIsZero (CASPoly [])   = True
casIsZero (CASFrac n _)   = casIsZero n
casIsZero _              = False

-- | Check if a CASValue is one
casIsOne :: CASValue -> Bool
casIsOne (CASInteger 1)                     = True
casIsOne (CASPoly [CASTerm (CASInteger 1) []]) = True
casIsOne _                                  = False

-- | Check if a CASValue is atomic (no parentheses needed for display)
-- Returns True for atomic values that don't need parentheses for display
casIsAtom :: CASValue -> Bool
casIsAtom (CASInteger _) = True
casIsAtom (CASFactor _)  = True
casIsAtom (CASPoly [])   = True   -- Zero
casIsAtom (CASPoly [CASTerm _ []])  = True   -- Integer only
casIsAtom (CASPoly [CASTerm (CASInteger 1) [_]]) = True  -- Single symbol with coeff 1
casIsAtom (CASFrac num (CASPoly [CASTerm (CASInteger 1) []])) = casIsAtom num  -- n/1 = n
casIsAtom _ = False

--------------------------------------------------------------------------------
-- Arithmetic Operations
--------------------------------------------------------------------------------

-- | Add two CASValues
casPlus :: CASValue -> CASValue -> CASValue
casPlus a b = casNormalize (casPlus' a b)

casPlus' :: CASValue -> CASValue -> CASValue
-- Integer + Integer
casPlus' (CASInteger a) (CASInteger b) = CASInteger (a + b)

-- Poly + Poly
casPlus' (CASPoly ts1) (CASPoly ts2) = CASPoly (ts1 ++ ts2)

-- Integer + Poly: embed integer as polynomial term
casPlus' (CASInteger n) (CASPoly ts) = CASPoly (CASTerm (CASInteger n) [] : ts)
casPlus' (CASPoly ts) (CASInteger n) = CASPoly (CASTerm (CASInteger n) [] : ts)

-- Frac + Frac: cross-multiply and add numerators
casPlus' (CASFrac n1 d1) (CASFrac n2 d2) =
  CASFrac (casPlus' (casMult' n1 d2) (casMult' n2 d1)) (casMult' d1 d2)

-- Frac + other: embed other as Frac
casPlus' (CASFrac n d) other = CASFrac (casPlus' n (casMult' other d)) d
casPlus' other (CASFrac n d) = CASFrac (casPlus' (casMult' other d) n) d

-- Factor handling: lift to polynomial before operation
casPlus' (CASFactor sym) other = casPlus' (liftFactorToPoly sym) other
casPlus' other (CASFactor sym) = casPlus' other (liftFactorToPoly sym)

-- | Negate a CASValue
casNegate :: CASValue -> CASValue
casNegate (CASInteger n)  = CASInteger (-n)
casNegate (CASPoly terms) = CASPoly (map negateTerm terms)
  where
    negateTerm (CASTerm coeff mono) = CASTerm (casNegate coeff) mono
casNegate (CASFrac n d)    = CASFrac (casNegate n) d
casNegate (CASFactor sym) = CASPoly [CASTerm (CASInteger (-1)) [(sym, 1)]]

-- | Subtract two CASValues
casMinus :: CASValue -> CASValue -> CASValue
casMinus a b = casPlus a (casNegate b)

-- | Multiply two CASValues
casMult :: CASValue -> CASValue -> CASValue
casMult a b = casNormalize (casMult' a b)

casMult' :: CASValue -> CASValue -> CASValue
-- Integer * Integer
casMult' (CASInteger a) (CASInteger b) = CASInteger (a * b)

-- Integer * Poly: scale all coefficients
casMult' (CASInteger n) (CASPoly ts) = CASPoly (map (scaleTerm n) ts)
  where
    scaleTerm k (CASTerm coeff mono) = CASTerm (casMult' (CASInteger k) coeff) mono
casMult' (CASPoly ts) (CASInteger n) = casMult' (CASInteger n) (CASPoly ts)

-- Poly * Poly: distribute
casMult' (CASPoly []) _ = CASPoly []
casMult' _ (CASPoly []) = CASPoly []
casMult' (CASPoly ts1) (CASPoly ts2) =
  CASPoly [multTerms t1 t2 | t1 <- ts1, t2 <- ts2]
  where
    multTerms (CASTerm c1 m1) (CASTerm c2 m2) =
      CASTerm (casMult' c1 c2) (combineMonomials m1 m2)

-- Frac * Frac: multiply numerators and denominators
casMult' (CASFrac n1 d1) (CASFrac n2 d2) =
  CASFrac (casMult' n1 n2) (casMult' d1 d2)

-- Frac * other: multiply into numerator
casMult' (CASFrac n d) other = CASFrac (casMult' n other) d
casMult' other (CASFrac n d) = CASFrac (casMult' other n) d

-- Factor handling: lift to polynomial before operation
casMult' (CASFactor sym) other = casMult' (liftFactorToPoly sym) other
casMult' other (CASFactor sym) = casMult' other (liftFactorToPoly sym)

-- | Lift a Factor to a polynomial: sym → 1 * sym^1
liftFactorToPoly :: SymbolExpr -> CASValue
liftFactorToPoly sym = CASPoly [CASTerm (CASInteger 1) [(sym, 1)]]

-- | Combine two monomials by adding exponents of matching symbols
combineMonomials :: Monomial -> Monomial -> Monomial
combineMonomials m1 m2 = foldr insertSymbol m2 m1
  where
    insertSymbol (sym, expo) mono =
      case lookup sym mono of
        Just _  -> map (\(s, e) -> if s == sym then (s, e + expo) else (s, e)) mono
        Nothing -> (sym, expo) : mono

-- | Divide two CASValues: a / b
casDivide :: CASValue -> CASValue -> CASValue
casDivide a b = casNormalize (CASFrac a b)

-- | Raise a CASValue to an integer power
casPower :: CASValue -> Integer -> CASValue
casPower _ 0 = CASInteger 1
casPower x 1 = x
casPower x n
  | n > 0     = casMult x (casPower x (n - 1))
  | otherwise = casDivide (CASInteger 1) (casPower x (-n))  -- Negative power

-- | Get the numerator of a CASValue
casNumerator :: CASValue -> CASValue
casNumerator (CASFrac num _) = num
casNumerator x              = x  -- Non-Frac values are their own numerator

-- | Get the denominator of a CASValue
casDenominator :: CASValue -> CASValue
casDenominator (CASFrac _ denom) = denom
casDenominator _                = CASInteger 1  -- Non-Frac values have denominator 1

--------------------------------------------------------------------------------
-- Normalization
--------------------------------------------------------------------------------

-- | Normalize a CASValue
casNormalize :: CASValue -> CASValue
casNormalize (CASInteger n) = CASInteger n
casNormalize (CASFactor sym) = CASFactor sym
casNormalize (CASPoly terms) = casNormalizePoly terms
casNormalize (CASFrac num denom) = casNormalizeFrac num denom

-- | Normalize a polynomial
-- Steps:
-- 1. Fold symbols within each term (x * x^2 → x^3)
-- 2. Remove zero-exponent symbols
-- 3. Fold terms with equal monomials
-- 4. Remove zero-coefficient terms
-- 5. Sort terms in descending order
casNormalizePoly :: [CASTerm] -> CASValue
casNormalizePoly terms =
  let -- Normalize each term's monomial
      terms1 = map normalizeTermMonomial terms
      -- Fold terms with equal monomials
      terms2 = foldTerms terms1
      -- Remove zero-coefficient terms
      terms3 = filter (not . isZeroTerm) terms2
      -- Sort in descending order (standard polynomial order)
      terms4 = sortTermsDescending terms3
  in case terms4 of
       []  -> CASInteger 0  -- Empty polynomial is zero
       [CASTerm coeff []] | isIntegerCoeff coeff -> extractInteger coeff
       ts  -> CASPoly ts
  where
    isZeroTerm (CASTerm coeff _) = casIsZero coeff
    isIntegerCoeff (CASInteger _) = True
    isIntegerCoeff _ = False
    extractInteger (CASInteger n) = CASInteger n
    extractInteger _ = error "extractInteger: not an integer"

-- | Normalize a term's monomial: combine duplicate symbols, remove zero exponents
normalizeTermMonomial :: CASTerm -> CASTerm
normalizeTermMonomial (CASTerm coeff mono) =
  let -- Fold duplicate symbols
      mono1 = foldMonomialSymbols mono
      -- Remove zero-exponent symbols
      mono2 = filter (\(_, exp) -> exp /= 0) mono1
      -- Normalize the coefficient recursively
      coeff' = casNormalize coeff
  in CASTerm coeff' mono2

-- | Fold duplicate symbols in a monomial by adding their exponents
foldMonomialSymbols :: Monomial -> Monomial
foldMonomialSymbols mono =
  let grouped = groupBy ((==) `on` fst) (sortBy (comparing (show . fst)) mono)
  in concatMap combineGroup grouped
  where
    combineGroup :: [(SymbolExpr, Integer)] -> [(SymbolExpr, Integer)]
    combineGroup [] = []
    combineGroup grp@((sym, _):_) = [(sym, sum (map snd grp))]

-- | Fold terms with equal monomials by adding their coefficients
foldTerms :: [CASTerm] -> [CASTerm]
foldTerms terms =
  let grouped = groupBy equalMonos (sortBy (comparing termMonoKey) terms)
  in concatMap combineTerms grouped
  where
    -- Use show-based key for consistent ordering
    termMonoKey (CASTerm _ m) = map (\(s, e) -> (show s, e)) (sortBy (comparing (show . fst)) m)
    termMono (CASTerm _ m) = sortBy (comparing (show . fst)) m
    equalMonos t1 t2 = termMono t1 == termMono t2
    combineTerms [] = []
    combineTerms grp@((CASTerm _ m):_) =
      let mono = sortBy (comparing (show . fst)) m
          coeffSum = foldr casPlus' (CASInteger 0) [c | CASTerm c _ <- grp]
      in [CASTerm (casNormalize coeffSum) mono]

-- | Sort terms in descending order (highest degree first)
-- Order: by total degree, then lexicographically by symbols
sortTermsDescending :: [CASTerm] -> [CASTerm]
sortTermsDescending = sortBy (flip (comparing termDegree) <> flip (comparing termSymbolsKey))
  where
    termDegree (CASTerm _ mono) = sum (map snd mono)
    -- Use show-based key for consistent lexicographic ordering
    termSymbolsKey (CASTerm _ mono) = map (\(s, e) -> (show s, e)) (sortBy (comparing (show . fst)) mono)

-- | Normalize a fraction
-- Steps:
-- 1. If denominator is 1, return numerator
-- 2. If numerator is 0, return 0
-- 3. Simplify using GCD
-- 4. Ensure positive denominator
casNormalizeFrac :: CASValue -> CASValue -> CASValue
casNormalizeFrac num denom =
  let num' = casNormalize num
      denom' = casNormalize denom
  in case (num', denom') of
       -- Zero numerator
       (n, _) | casIsZero n -> CASInteger 0
       -- Denominator is 1
       (n, d) | casIsOne d -> n
       -- Denominator is -1: negate numerator
       (n, CASInteger (-1)) -> casNegate n
       -- Integer / Integer: reduce by GCD and normalize sign
       (CASInteger n, CASInteger d) ->
         let g = gcd n d
             -- Normalize sign: ensure positive denominator
             sign = if d < 0 then -1 else 1
             n' = sign * (n `div` g)
             d' = abs (d `div` g)
         in if d' == 1
            then CASInteger n'
            else CASFrac (CASInteger n') (CASInteger d')
       -- Poly / Integer: divide each coefficient by the integer
       (CASPoly ts1, CASInteger d) ->
         let g = casTermsGcdCoeff ts1 d
             sign = if d < 0 then -1 else 1
             d' = abs (d `div` g)
             ts1' = map (\(CASTerm c m) -> CASTerm (divCoeffBy c g sign) m) ts1
         in if d' == 1
            then casNormalizePoly ts1'
            else CASFrac (casNormalizePoly ts1') (CASInteger d')
       -- Poly / Poly: try to reduce by monomial GCD
       (CASPoly ts1, CASPoly ts2) ->
         let (ts1', ts2') = simplifyPolyDiv ts1 ts2
         in case (ts1', ts2') of
              (ts1'', [CASTerm (CASInteger 1) []]) -> casNormalizePoly ts1''
              _ -> CASFrac (casNormalizePoly ts1') (casNormalizePoly ts2')
       -- a / (b / c) = (a * c) / b
       (n, CASFrac b c) -> casNormalizeFrac (casMult n c) b
       -- (a / b) / c = a / (b * c)
       (CASFrac a b, c) -> casNormalizeFrac a (casMult b c)
       -- Default: no simplification
       _ -> CASFrac num' denom'

-- | Compute GCD of polynomial coefficients with an integer
casTermsGcdCoeff :: [CASTerm] -> Integer -> Integer
casTermsGcdCoeff [] d = abs d
casTermsGcdCoeff terms d = foldl gcdWithTerm (abs d) terms
  where
    gcdWithTerm acc (CASTerm (CASInteger c) _) = gcd acc (abs c)
    gcdWithTerm acc _ = acc  -- Non-integer coefficient: GCD = 1 effectively

-- | Divide a coefficient by integer, applying sign
divCoeffBy :: CASValue -> Integer -> Integer -> CASValue
divCoeffBy (CASInteger c) g sign = CASInteger (sign * (c `div` g))
divCoeffBy c _ _ = c  -- Fallback: keep as-is for non-integer

-- | Simplify polynomial division by extracting common monomial GCD
simplifyPolyDiv :: [CASTerm] -> [CASTerm] -> ([CASTerm], [CASTerm])
simplifyPolyDiv [] ts2 = ([], ts2)
simplifyPolyDiv ts1 [] = (ts1, [])
simplifyPolyDiv ts1 ts2 =
  let gcdTerm = casTermsGcd (ts1 ++ ts2)
  in (map (`divideTermBy` gcdTerm) ts1, map (`divideTermBy` gcdTerm) ts2)

--------------------------------------------------------------------------------
-- GCD Operations
--------------------------------------------------------------------------------

-- | GCD of two CASValues (for coefficient reduction)
-- Initial implementation: only handles CASInteger, others return 1
casGcd :: CASValue -> CASValue -> CASValue
casGcd (CASInteger a) (CASInteger b) = CASInteger (gcd a b)
casGcd _ _ = CASInteger 1  -- Fallback: GCD = 1 for other coefficient types

-- | Compute the GCD of a list of terms (coefficient GCD + monomial GCD)
casTermsGcd :: [CASTerm] -> CASTerm
casTermsGcd [] = CASTerm (CASInteger 1) []
casTermsGcd [t] = t
casTermsGcd terms = foldl1 termGcd terms
  where
    termGcd (CASTerm c1 m1) (CASTerm c2 m2) =
      CASTerm (casGcd c1 c2) (monoGcd m1 m2)

-- | GCD of two monomials: take minimum exponent for each shared symbol
monoGcd :: Monomial -> Monomial -> Monomial
monoGcd [] _ = []
monoGcd ((sym, expo):rest) mono =
  case lookup sym mono of
    Just exp' -> (sym, min expo exp') : monoGcd rest mono
    Nothing   -> monoGcd rest mono

-- | Divide a term by another term (for GCD reduction)
divideTermBy :: CASTerm -> CASTerm -> CASTerm
divideTermBy (CASTerm coeff1 mono1) (CASTerm coeff2 mono2) =
  CASTerm (divCoeff coeff1 coeff2) (divMono mono1 mono2)
  where
    divCoeff (CASInteger a) (CASInteger b) = CASInteger (a `div` b)
    divCoeff a _ = a  -- Fallback: no division for other types

    divMono m [] = m
    divMono m ((sym, expo):rest) =
      let m' = map (\(s, e) -> if s == sym then (s, e - expo) else (s, e)) m
      in divMono m' rest

--------------------------------------------------------------------------------
-- Pattern Synonyms for CASValue
--------------------------------------------------------------------------------

-- | Pattern for zero value
pattern CASZero :: CASValue
pattern CASZero = CASInteger 0

-- | Pattern for a single symbol: sym → 1 * sym^1
pattern CASSingleSymbol :: SymbolExpr -> CASValue
pattern CASSingleSymbol sym = CASPoly [CASTerm (CASInteger 1) [(sym, 1)]]

-- | Pattern for a single term: coeff * mono
pattern CASSingleTerm :: Integer -> Monomial -> CASValue
pattern CASSingleTerm coeff mono = CASPoly [CASTerm (CASInteger coeff) mono]

--------------------------------------------------------------------------------
-- Pattern Matching (control-egison matchers)
--------------------------------------------------------------------------------

-- | Matcher for CASValue
data CASM = CASM
instance Matcher CASM CASValue

-- | Matcher for CASTerm
data CASTermM = CASTermM
instance Matcher CASTermM CASTerm

-- | Matcher for SymbolExpr (CAS version)
data CASSymbolM = CASSymbolM
instance Matcher CASSymbolM SymbolExpr

-- | Match a term and extract its coefficient and monomial
casTerm' :: Pattern (PP CASValue, PP Monomial) CASTermM CASTerm (CASValue, Monomial)
casTerm' _ _ (CASTerm coeff mono) = pure (coeff, mono)
-- | Matcher decomposition for casTerm' pattern
casTerm'M :: CASTermM -> CASTerm -> (CASM, Multiset (CASSymbolM, Eql))
casTerm'M CASTermM _ = (CASM, Multiset (CASSymbolM, Eql))
casTermM :: CASTermM -> CASTerm -> (CASM, Multiset (CASSymbolM, Eql))
casTermM CASTermM _ = (CASM, Multiset (CASSymbolM, Eql))

-- | Match a symbol and extract its name
casSymbol :: Pattern (PP String) CASSymbolM SymbolExpr String
casSymbol _ _ (Symbol _ name []) = pure name
casSymbol _ _ _                  = mzero
casSymbolM :: CASSymbolM -> p -> Eql
casSymbolM CASSymbolM _ = Eql

-- | Match a function and extract its name and arguments
casFunc :: Pattern (PP CASValue, PP [CASValue])
                CASSymbolM SymbolExpr (CASValue, [CASValue])
casFunc _ _ (FunctionData name args) = pure (name, args)
casFunc _ _ _                        = mzero
casFuncM :: CASSymbolM -> SymbolExpr -> (CASM, List CASM)
casFuncM CASSymbolM _ = (CASM, List CASM)

-- | Match Apply1 and extract function name, WHNF, and argument
casApply1 :: Pattern (PP String, PP WHNFData, PP CASValue) CASSymbolM SymbolExpr (String, WHNFData, CASValue)
casApply1 _ _ (Apply1 (CASSingleSymbol (QuoteFunction fnWhnf)) a1) =
  case prettyFunctionName fnWhnf of
    Just fn -> pure (fn, fnWhnf, a1)
    Nothing -> mzero
casApply1 _ _ _ = mzero
casApply1M :: CASSymbolM -> p -> (Eql, Something, CASM)
casApply1M CASSymbolM _ = (Eql, Something, CASM)

-- | Match Apply2 and extract function name, WHNF, and arguments
casApply2 :: Pattern (PP String, PP WHNFData, PP CASValue, PP CASValue) CASSymbolM SymbolExpr (String, WHNFData, CASValue, CASValue)
casApply2 _ _ (Apply2 (CASSingleSymbol (QuoteFunction fnWhnf)) a1 a2) =
  case prettyFunctionName fnWhnf of
    Just fn -> pure (fn, fnWhnf, a1, a2)
    Nothing -> mzero
casApply2 _ _ _ = mzero
casApply2M :: CASSymbolM -> p -> (Eql, Something, CASM, CASM)
casApply2M CASSymbolM _ = (Eql, Something, CASM, CASM)

-- | Match Apply3 and extract function name, WHNF, and arguments
casApply3 :: Pattern (PP String, PP WHNFData, PP CASValue, PP CASValue, PP CASValue) CASSymbolM SymbolExpr (String, WHNFData, CASValue, CASValue, CASValue)
casApply3 _ _ (Apply3 (CASSingleSymbol (QuoteFunction fnWhnf)) a1 a2 a3) =
  case prettyFunctionName fnWhnf of
    Just fn -> pure (fn, fnWhnf, a1, a2, a3)
    Nothing -> mzero
casApply3 _ _ _ = mzero
casApply3M :: CASSymbolM -> p -> (Eql, Something, CASM, CASM, CASM)
casApply3M CASSymbolM _ = (Eql, Something, CASM, CASM, CASM)

-- | Match Apply4 and extract function name, WHNF, and arguments
casApply4 :: Pattern (PP String, PP WHNFData, PP CASValue, PP CASValue, PP CASValue, PP CASValue) CASSymbolM SymbolExpr (String, WHNFData, CASValue, CASValue, CASValue, CASValue)
casApply4 _ _ (Apply4 (CASSingleSymbol (QuoteFunction fnWhnf)) a1 a2 a3 a4) =
  case prettyFunctionName fnWhnf of
    Just fn -> pure (fn, fnWhnf, a1, a2, a3, a4)
    Nothing -> mzero
casApply4 _ _ _ = mzero
casApply4M :: CASSymbolM -> p -> (Eql, Something, CASM, CASM, CASM, CASM)
casApply4M CASSymbolM _ = (Eql, Something, CASM, CASM, CASM, CASM)

-- | Match Quote and extract the inner CASValue
casQuote :: Pattern (PP CASValue) CASSymbolM SymbolExpr CASValue
casQuote _ _ (Quote m) = pure m
casQuote _ _ _         = mzero

-- | Match Quote and extract the negated inner CASValue
casNegQuote :: Pattern (PP CASValue) CASSymbolM SymbolExpr CASValue
casNegQuote _ _ (Quote m) = pure (casNegate m)
casNegQuote _ _ _         = mzero
casNegQuoteM :: CASSymbolM -> p -> CASM
casNegQuoteM CASSymbolM _ = CASM

-- | Match QuoteFunction and extract function name and WHNF
casQuoteFunction :: Pattern (PP String, PP WHNFData) CASSymbolM SymbolExpr (String, WHNFData)
casQuoteFunction _ _ (QuoteFunction whnf) = case prettyFunctionName whnf of
  Just name -> pure (name, whnf)
  Nothing   -> mzero
casQuoteFunction _ _ _ = mzero
casQuoteFunctionM :: CASSymbolM -> p -> Eql
casQuoteFunctionM CASSymbolM _ = Eql

-- | Match equal monomial (checks if two monomials are equal, handling sign)
casEqualMonomial :: Pattern (PP Integer, PP Monomial) (Multiset (CASSymbolM, Eql)) Monomial (Integer, Monomial)
casEqualMonomial (_, VP xs) _ ys = case casIsEqualMonomial xs ys of
                                  Just sgn -> pure (sgn, xs)
                                  Nothing  -> mzero
casEqualMonomial _ _ _ = mzero
casEqualMonomialM :: Multiset (CASSymbolM, Eql) -> p -> (Eql, Multiset (CASSymbolM, Eql))
casEqualMonomialM (Multiset (CASSymbolM, Eql)) _ = (Eql, Multiset (CASSymbolM, Eql))

-- | Check if two monomials are equal, returning sign if so
casIsEqualMonomial :: Monomial -> Monomial -> Maybe Integer
casIsEqualMonomial xs ys =
  match dfs (xs, ys) (Multiset (CASSymbolM, Eql), Multiset (CASSymbolM, Eql))
    [ [mc| ((casQuote $s, $n) : $xss, (casNegQuote #s, #n) : $yss) ->
             case casIsEqualMonomial xss yss of
               Nothing -> Nothing
               Just sgn -> return (if even n then sgn else - sgn) |]
    , [mc| (($x, $n) : $xss, (#x, #n) : $yss) -> casIsEqualMonomial xss yss |]
    , [mc| ([], []) -> return 1 |]
    , [mc| _ -> Nothing |]
    ]

-- | Match zero CASValue
casZero :: Pattern () CASM CASValue ()
casZero _ _ CASZero    = pure ()
casZero _ _ (CASPoly []) = pure ()  -- Empty polynomial is also zero
casZero _ _ _          = mzero
casZeroM :: CASM -> p -> ()
casZeroM CASM _ = ()

-- | Match a single term in CASValue and extract coefficient, denominator coefficient, and monomial
casSingleTerm :: Pattern (PP Integer, PP Integer, PP Monomial) CASM CASValue (Integer, Integer, Monomial)
casSingleTerm _ _ (CASFrac (CASPoly [CASTerm (CASInteger c) mono]) (CASPoly [CASTerm (CASInteger c2) []])) = pure (c, c2, mono)
casSingleTerm _ _ (CASFrac (CASSingleTerm c mono) (CASInteger c2)) = pure (c, c2, mono)
casSingleTerm _ _ (CASPoly [CASTerm (CASInteger c) mono]) = pure (c, 1, mono)
casSingleTerm _ _ (CASInteger n) = pure (n, 1, [])  -- Integer is a single term with empty monomial
casSingleTerm _ _ _ = mzero
casSingleTermM :: CASM -> p -> (Eql, Eql, Multiset (CASSymbolM, Eql))
casSingleTermM CASM _ = (Eql, Eql, Multiset (CASSymbolM, Eql))

-- | ValuePattern instance for CASM
instance ValuePattern CASM CASValue where
  value e () CASM v = if e == v then pure () else mzero

-- | ValuePattern instance for CASSymbolM
instance ValuePattern CASSymbolM SymbolExpr where
  value e () CASSymbolM v = if e == v then pure () else mzero
